# Generated by Django 5.0.7 on 2024-08-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='texto',
            new_name='text',
        ),
    ]
